package io.imulab.nix.oauth.response

import io.imulab.nix.oauth.reserved.Param
import io.imulab.nix.oauth.reserved.space

/**
 * Response that returns an authorize code
 */
data class AuthorizeCodeResponse(
    /**
     * The authorization code generated by the authorization server.
     */
    var code: String = "",
    /**
     * The state from the authorize request, if any.
     */
    var state: String? = null,
    /**
     * The array of granted scopes, if different with the requested values.
     */
    var scope: Set<String>? = null
) : OAuthResponse {

    override val status: Int
        get() = 200
    override val headers: Map<String, String>
        get() = mapOf(
            "Cache-Control" to "no-store",
            "Pragma" to "no-cache"
        )
    override val data: Map<String, String>
        get() {
            check(code.isNotEmpty())

            return mutableMapOf(Param.code to code).also {
                if (!scope.isNullOrEmpty())
                    it[Param.scope] = scope!!.joinToString(separator = space)
                if (!state.isNullOrBlank())
                    it[Param.state] = state!!
            }
        }
}